image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1556.12291,    0.     ,  608.934  ,
            0.     , 1556.33489,  529.08752,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.100468, 0.209622, -0.001859, -0.002212, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1539.91383,    0.     ,  606.99942,    0.     ,
            0.     , 1543.27254,  528.30592,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]